# Database module

from .connection import get_db, init_db, close_db, AsyncSessionLocal
from .models import (
    Base,
    Partner,
    Branch,
    PartnerBranch,
    PartnerStatus,
    BroadcastHistory,
    NetworkRating,
    NetworkRatingHistory,
    YClientsCompany,
    PartnerCompany,
    RequestLog,
    RequestType,
    RequestStatus,
    Poll,
    PollOption,
    PollResponse,
    PollMessage,
    PollStatus,
    DepartmentInfo,
    DepartmentType,
    DepartmentInfoType,
)
from .crud import (
    get_partner_by_telegram_id,
    get_partner_by_phone,
    create_partner,
    update_partner_status,
    get_all_partners,
    get_pending_partners,
    get_all_branches,
    create_branch,
    get_or_create_branch,
    link_partner_to_branch,
    get_partner_branches,
    update_partner_for_branch_request,
    get_partner_by_id,
    delete_partner,
    clear_partner_pending_branch,
    get_partners_with_pending_branches,
    get_network_rating_by_company,
    update_network_rating,
    get_all_network_ratings,
    get_last_network_rating_update,
    save_rating_history,
    get_rating_history,
    get_previous_month_ranks,
    # YClients Companies
    sync_yclients_companies,
    get_all_yclients_companies,
    get_yclients_company_by_id,
    link_partner_to_company,
    get_partner_companies,
    # Request Log
    create_request_log,
    get_request_logs,
    # Polls
    create_poll,
    get_poll_by_id,
    get_all_polls,
    update_poll_status,
    save_poll_message,
    save_poll_response,
    get_poll_messages,
    mark_poll_message_stopped,
    delete_poll,
    get_poll_results,
    # Department Info (Полезное)
    get_department_info,
    get_all_department_info,
    upsert_department_info,
    init_default_department_info,
)

__all__ = [
    # Connection
    "get_db",
    "init_db", 
    "close_db",
    "AsyncSessionLocal",
    # Models
    "Base",
    "Partner",
    "Branch",
    "PartnerBranch",
    "PartnerStatus",
    "NetworkRating",
    "NetworkRatingHistory",
    "YClientsCompany",
    "PartnerCompany",
    "Poll",
    "PollOption",
    "PollResponse",
    "PollMessage",
    "PollStatus",
    # CRUD
    "get_partner_by_telegram_id",
    "get_partner_by_phone",
    "create_partner",
    "update_partner_status",
    "get_all_partners",
    "get_pending_partners",
    "get_all_branches",
    "create_branch",
    "get_or_create_branch",
    "link_partner_to_branch",
    "get_partner_branches",
    "update_partner_for_branch_request",
    "get_partner_by_id",
    "delete_partner",
    "clear_partner_pending_branch",
    "get_partners_with_pending_branches",
    "get_network_rating_by_company",
    "update_network_rating",
    "get_all_network_ratings",
    "get_last_network_rating_update",
    "save_rating_history",
    "get_rating_history",
    "get_previous_month_ranks",
    # YClients Companies
    "sync_yclients_companies",
    "get_all_yclients_companies",
    "get_yclients_company_by_id",
    "link_partner_to_company",
    "get_partner_companies",
    # Request Log
    "RequestLog",
    "RequestType",
    "RequestStatus",
    "create_request_log",
    "get_request_logs",
    # Polls
    "create_poll",
    "get_poll_by_id",
    "get_all_polls",
    "update_poll_status",
    "save_poll_message",
    "save_poll_response",
    "get_poll_messages",
    "mark_poll_message_stopped",
    "delete_poll",
    "get_poll_results",
    # Department Info (Полезное)
    "DepartmentInfo",
    "DepartmentType",
    "DepartmentInfoType",
    "get_department_info",
    "get_all_department_info",
    "upsert_department_info",
    "init_default_department_info",
]

