"""add network_rating_history table

Revision ID: 089146dec083
Revises: a40d3936c531
Create Date: 2025-11-28 21:29:11.881811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '089146dec083'
down_revision: Union[str, None] = 'a40d3936c531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_rating', 'avg_check',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('network_rating', 'previous_rank',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('network_rating_history', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('network_rating_history', 'avg_check',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('network_rating_history', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('network_rating_history', 'total_companies',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('network_rating_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_network_rating_history_company', table_name='network_rating_history')
    op.drop_index('ix_network_rating_history_year_month', table_name='network_rating_history')
    op.create_index(op.f('ix_network_rating_history_month'), 'network_rating_history', ['month'], unique=False)
    op.create_index(op.f('ix_network_rating_history_yclients_company_id'), 'network_rating_history', ['yclients_company_id'], unique=False)
    op.create_index(op.f('ix_network_rating_history_year'), 'network_rating_history', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_rating_history_year'), table_name='network_rating_history')
    op.drop_index(op.f('ix_network_rating_history_yclients_company_id'), table_name='network_rating_history')
    op.drop_index(op.f('ix_network_rating_history_month'), table_name='network_rating_history')
    op.create_index('ix_network_rating_history_year_month', 'network_rating_history', ['year', 'month'], unique=False)
    op.create_index('ix_network_rating_history_company', 'network_rating_history', ['yclients_company_id'], unique=False)
    op.alter_column('network_rating_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('network_rating_history', 'total_companies',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('network_rating_history', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('network_rating_history', 'avg_check',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('network_rating_history', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('network_rating', 'previous_rank',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('network_rating', 'avg_check',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###

