"""add department_info table

Revision ID: 208987b7ff51
Revises: d8b07abaac93
Create Date: 2025-11-29 19:29:31.968721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208987b7ff51'
down_revision: Union[str, None] = 'd8b07abaac93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('DEVELOPMENT', 'MARKETING', 'DESIGN', name='departmenttype'), nullable=False),
    sa.Column('info_type', sa.Enum('IMPORTANT_INFO', 'CONTACT_INFO', name='departmentinfotype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_info_department'), 'department_info', ['department'], unique=False)
    op.create_index(op.f('ix_department_info_info_type'), 'department_info', ['info_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_info_info_type'), table_name='department_info')
    op.drop_index(op.f('ix_department_info_department'), table_name='department_info')
    op.drop_table('department_info')
    # ### end Alembic commands ###

