"""add_has_pending_branch

Revision ID: 35af65bccacc
Revises: d69a899495b5
Create Date: 2025-11-27 20:14:08.683093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35af65bccacc'
down_revision: Union[str, None] = 'd69a899495b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('has_pending_branch', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'has_pending_branch')
    # ### end Alembic commands ###

