"""add request_logs table

Revision ID: 370bb292e461
Revises: 8abeac55102f
Create Date: 2025-11-28 23:25:11.643937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370bb292e461'
down_revision: Union[str, None] = '8abeac55102f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('VERIFICATION', 'ADD_BARBERSHOP', name='requesttype'), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_created_at'), 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_partner_id'), 'request_logs', ['partner_id'], unique=False)
    op.create_index(op.f('ix_request_logs_request_type'), 'request_logs', ['request_type'], unique=False)
    op.create_index(op.f('ix_request_logs_status'), 'request_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_status'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_request_type'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_partner_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_created_at'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###

