"""add department_buttons table

Revision ID: 741c5006b13b
Revises: 208987b7ff51
Create Date: 2025-11-29 21:37:56.848811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741c5006b13b'
down_revision: Union[str, None] = '208987b7ff51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('DEVELOPMENT', 'MARKETING', 'DESIGN', name='departmenttype'), nullable=False),
    sa.Column('button_text', sa.String(length=100), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_buttons_department'), 'department_buttons', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_buttons_department'), table_name='department_buttons')
    op.drop_table('department_buttons')
    # ### end Alembic commands ###

