"""add yclients_companies and partner_companies tables

Revision ID: 8abeac55102f
Revises: 96e68c0e874d
Create Date: 2025-11-28 22:11:43.114895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abeac55102f'
down_revision: Union[str, None] = '96e68c0e874d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

