"""add yclients_companies and partner_companies tables

Revision ID: 96e68c0e874d
Revises: 089146dec083
Create Date: 2025-11-28 22:11:15.697329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e68c0e874d'
down_revision: Union[str, None] = '089146dec083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yclients_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yclients_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_million_city', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yclients_companies_city'), 'yclients_companies', ['city'], unique=False)
    op.create_index(op.f('ix_yclients_companies_region'), 'yclients_companies', ['region'], unique=False)
    op.create_index(op.f('ix_yclients_companies_yclients_id'), 'yclients_companies', ['yclients_id'], unique=True)
    op.create_table('partner_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['yclients_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_companies')
    op.drop_index(op.f('ix_yclients_companies_yclients_id'), table_name='yclients_companies')
    op.drop_index(op.f('ix_yclients_companies_region'), table_name='yclients_companies')
    op.drop_index(op.f('ix_yclients_companies_city'), table_name='yclients_companies')
    op.drop_table('yclients_companies')
    # ### end Alembic commands ###

