"""Add yclients_id, display_name, branches_text

Revision ID: 9c2e5324bbc6
Revises: a7d1ba42eef7
Create Date: 2025-11-27 19:31:51.886613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2e5324bbc6'
down_revision: Union[str, None] = 'a7d1ba42eef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

