"""Add yclients_id, display_name, branches_text

Revision ID: a7d1ba42eef7
Revises: 136f6fd998f5
Create Date: 2025-11-27 19:27:38.840856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d1ba42eef7'
down_revision: Union[str, None] = '136f6fd998f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('yclients_id', sa.String(length=50), nullable=True))
    op.add_column('branches', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_branches_yclients_id'), 'branches', ['yclients_id'], unique=True)
    op.add_column('partners', sa.Column('telegram_first_name', sa.String(length=100), nullable=True))
    op.add_column('partners', sa.Column('telegram_last_name', sa.String(length=100), nullable=True))
    op.add_column('partners', sa.Column('branches_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'branches_text')
    op.drop_column('partners', 'telegram_last_name')
    op.drop_column('partners', 'telegram_first_name')
    op.drop_index(op.f('ix_branches_yclients_id'), table_name='branches')
    op.drop_column('branches', 'display_name')
    op.drop_column('branches', 'yclients_id')
    # ### end Alembic commands ###

