"""add_has_pending_branch_to_partner

Revision ID: d69a899495b5
Revises: 9c2e5324bbc6
Create Date: 2025-11-27 20:08:04.247582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69a899495b5'
down_revision: Union[str, None] = '9c2e5324bbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

